Billing history beginning [WIP]
codex-team/hawk.garage pull request #307
Opened 2020-08-03 17:59 UTC by neSpecc

Resolves #284

2020-09-01 17:06 UTC, ilyamore88 commented on src/api/billing/index.ts
> +import {BusinessOperation} from '../../types/business-operation';
Линтер

2020-09-01 17:15 UTC, ilyamore88 commented on src/components/workspace/settings/Billing.vue
> +   * @param to
Нет доков к параметрам, как и типов параметров в функции

2020-09-01 17:15 UTC, ilyamore88 commented on src/components/workspace/settings/Layout.vue
> +          :to="{ name: 'workspace-settings-billing', params: {workspaceId: workspace.id} }"
Линтер

2020-09-01 17:15 UTC, ilyamore88 commented on src/i18n/messages/en.json
> +      "paymentByCard": "Payment by card **** **** ***** {cardPan}",
```suggestion
      "paymentByCard": "Payment by card **** **** **** {cardPan}",
```

2020-09-01 17:15 UTC, ilyamore88 commented on src/i18n/messages/ru.json
> +      "paymentByCard": "Пополнение по карте **** **** ***** {cardPan}",
```suggestion
      "paymentByCard": "Пополнение по карте **** **** **** {cardPan}",
```

2020-09-01 17:15 UTC, ilyamore88 commented on src/types/business-operation.d.ts
> +import {BusinessOperationType} from './business-operation-type';
Линтер

2020-09-02 16:48 UTC, gohabereg requested changes

2020-09-02 16:48 UTC, gohabereg commented on src/components/utils/billing/History.vue
> +    operationsFiltered(): BusinessOperation[] {
`filteredOperations`

2020-09-02 16:48 UTC, gohabereg commented on src/components/utils/billing/History.vue
> +    const filter = {
Можно же это сделать енамом 
```
enum Filter {
  All,
  Incoming,
  Charges
}
```

2020-09-02 16:48 UTC, gohabereg commented on src/components/utils/billing/History.vue
> +    applyFilter(filter: number): void {
Если enum определить выше скоупа компонента, то здесь можно будет указать `filter: Filter`

2020-09-02 16:48 UTC, gohabereg commented on src/components/workspace/settings/Billing.vue
> +    isPaymentsHistoryLoading: boolean,
Имхо, лучше вынести в интерфейс

2020-09-02 16:48 UTC, gohabereg commented on src/i18n/messages/ru.json
> +      "chargeForPlan": "Списание за тарифный план {workspaceName}"
Может указывать еще и название плана?

2020-09-02 16:48 UTC, gohabereg commented on src/types/business-operation-status.ts
> +  Pending='PENDING',
```suggestion
  Pending = 'PENDING',
```

2020-09-02 16:48 UTC, gohabereg commented on src/types/business-operation-status.ts
> +  Confirmed='CONFIRMED',
```suggestion
  Confirmed = 'CONFIRMED',
```

2020-09-02 16:48 UTC, gohabereg commented on src/types/business-operation-status.ts
> +  Rejected='REJECTED'
```suggestion
  Rejected = 'REJECTED'
```

2020-09-02 16:48 UTC, gohabereg commented on src/types/business-operation-type.ts
> +  WorkspacePlanPurchase='WORKSPACE_PLAN_PURCHASE',
```suggestion
  WorkspacePlanPurchase = 'WORKSPACE_PLAN_PURCHASE',
```

2020-09-02 16:48 UTC, gohabereg commented on src/types/business-operation-type.ts
> +  DepositByUser='DEPOSIT_BY_USER'
```suggestion
  DepositByUser = 'DEPOSIT_BY_USER'
```

2020-09-06 09:55 UTC, neSpecc commented on src/i18n/messages/ru.json
> +      "chargeForPlan": "Списание за тарифный план {workspaceName}"
Если только отдельной фичей допилить, тк у нас в пейлоаде этой операции сейчас не хранится план

```ts

/**
 * Business operation payload type for `WorkspacePlanPurchase` operation type
 */
export interface PayloadOfWorkspacePlanPurchase {
  /**
   * Workspace to which the payment is debited
   */
  workspace: Workspace;

  /**
   * Amount of payment
   */
  amount: number;
}
```

2020-09-06 12:28 UTC, neSpecc commented on src/components/utils/billing/History.vue
> +    operationsFiltered(): BusinessOperation[] {
переделал

2020-09-06 12:28 UTC, neSpecc commented on src/types/business-operation.d.ts
> +import {BusinessOperationType} from './business-operation-type';
поправил

2020-09-06 13:22 UTC, ilyamore88 approved these changes

2020-09-07 13:01 UTC, gohabereg approved these changes

2020-09-07 13:01 UTC, nikmel2803 approved these changes

2020-09-07 13:34 UTC, merged