Add updates after plan change
codex-team/hawk.garage pull request #331
Opened 2020-10-07 17:29 UTC by GeekaN2

2020-10-19 16:52 UTC, ilyamore88 requested changes

2020-10-19 16:52 UTC, ilyamore88 commented on src/api/workspaces/index.ts
> + * @param {Array} ids – id of fetching workspaces balance
Тип отличается от типа в функции. Вроде бы в ts файлах в принципе договаривались не указывать типы и returns в комментариях.

2020-10-19 16:52 UTC, ilyamore88 commented on src/api/workspaces/index.ts
> +export async function getBalance(ids: string): Promise<Workspace> {
Я так понимаю, что функция должна принимать в параметре ids массив string, но по типизации это почему-то обычный string.

2020-10-23 18:36 UTC, nikmel2803 approved these changes

2020-10-27 18:26 UTC, ilyamore88 approved these changes

2020-10-27 18:27 UTC, merged