[Fix] Error while saving profile info, autocomplete in form fields
codex-team/hawk.garage pull request #338
Opened 2020-11-16 15:46 UTC by ilyamore88

Localizes message about an error while saving profile info. Adds type="email" to input field (Closes #335).
![image](https://user-images.githubusercontent.com/37909603/99274713-b2084500-283b-11eb-8752-0771bd86e18c.png)
![image](https://user-images.githubusercontent.com/37909603/99274738-ba608000-283b-11eb-8ad7-db4755380fa7.png)

Adds autocomplete attributes to form fields (see https://web.dev/sign-in-form-best-practices/#autofill).
For example, Chrome now prompts you to generate a new strong password:
![image](https://user-images.githubusercontent.com/37909603/99274791-cb10f600-283b-11eb-92a1-b0a078bb9954.png)

2020-11-16 15:52 UTC, neSpecc requested changes

2020-11-16 15:52 UTC, neSpecc commented on src/i18n/messages/en.json
> +        "Cannot read property updateProfile of null": "Failed to save profile settings"
> Cannot read property updateProfile of null 

надо не писать перевод на эту ошибку, а пофиксить (обработать) ее. А перевод надо писать уже на нашу кастомную ошибку

2020-11-16 16:11 UTC, ilyamore88 commented on src/i18n/messages/en.json
> +        "Cannot read property updateProfile of null": "Failed to save profile settings"
Done
![image](https://user-images.githubusercontent.com/37909603/99277876-6e173f00-283f-11eb-8485-557f5a92905f.png)

2020-11-17 17:51 UTC, nikmel2803 approved these changes

2020-11-20 20:16 UTC, talyguryn approved these changes

2020-11-20 20:33 UTC, neSpecc approved these changes

2020-11-22 15:41 UTC, merged