fix(repetitions): add check for addons existing for repetitions
codex-team/hawk.garage pull request #345
Opened 2020-12-03 08:06 UTC by talyguryn

TypeError: null is not an object (evaluating 'e.payload.addons.url')

2020-12-03 08:06 UTC, talyguryn commented
![image](https://user-images.githubusercontent.com/15259299/100981266-a022e380-3557-11eb-8ed9-055ec4d63016.png)

2020-12-03 08:39 UTC, neSpecc requested changes

2020-12-03 08:39 UTC, neSpecc commented on src/components/event/RepetitionsList.vue
> +        <td
нельзя выбрасывать ячейку

2021-06-30 12:50 UTC, neSpecc commented on src/components/event/RepetitionsList.vue
> +              {{ repetition.payload.user ? repetition.payload.user.name || '—' : 'Unknown' }}
i18n

2021-07-01 07:19 UTC, neSpecc approved these changes

2021-07-01 08:26 UTC, nikmel2803 approved these changes

2021-07-01 17:01 UTC, ilyamore88 approved these changes

2021-07-01 17:07 UTC, merged