Feature: pay widget
codex-team/hawk.garage pull request #354
Opened 2021-01-21 22:01 UTC by talyguryn

Integrate cloudpayments widget

2021-01-30 14:28 UTC, neSpecc requested changes

2021-01-30 14:28 UTC, neSpecc commented on src/components/modals/ProcessPaymentDialog.vue
> +    if (window.cp && window.cp.CloudPayments) return;
```suggestion
    if (window.cp && window.cp.CloudPayments) {
      return;
    }
```

2021-01-30 14:28 UTC, neSpecc commented on src/components/modals/ProcessPaymentDialog.vue
> +    const amount = +this.amount;
useless variable

2021-01-30 14:28 UTC, neSpecc commented on src/components/modals/ProcessPaymentDialog.vue
> +        description: `Add funds for ${this.workspace.name.toString()} workspace`,
Adding funds for the ${tarif} plan for ${workspace} workspace

2021-01-30 14:28 UTC, neSpecc commented on src/components/modals/ProcessPaymentDialog.vue
> +        }
missed type definition

2021-01-30 14:28 UTC, neSpecc commented on src/components/modals/ProcessPaymentDialog.vue
>    async processPayment(): Promise<void> {
were Promise?

2021-01-31 18:04 UTC, neSpecc commented on src/components/modals/ProcessPaymentDialog.vue
> +        description: `Activate tariff "${tariff}" for ${this.workspace.name.toString()} workspace for a month`,
формулировка не очень. Надо сказать "Оплата за тарифный план P для воркспейса W"

2021-01-31 18:04 UTC, neSpecc commented on src/types/cloudpayments-data.d.ts
> +export interface CloudpaymentsData {
```suggestion
export interface PlanProlongationPayload {
```

2021-02-02 11:39 UTC, neSpecc requested changes

2021-02-02 11:39 UTC, neSpecc commented on src/components/modals/ProcessPaymentDialog.vue
> +        invoiceId: `${this.workspace.name.toString()}`,
здесь должно быть кодовое название платежа, типа `CDX 21-01 Basic` (от CodeX за январь 2021, за план Basic)

2021-02-02 11:40 UTC, talyguryn commented on src/components/modals/ProcessPaymentDialog.vue
> +        invoiceId: `${this.workspace.name.toString()}`,
это можно сделать позже

2021-02-02 11:41 UTC, neSpecc commented on src/components/modals/ProcessPaymentDialog.vue
> +      // @todo set lang from user's Hawk setting
комменты не по стандарту

2021-02-02 11:42 UTC, neSpecc commented on src/components/modals/ProcessPaymentDialog.vue
> +        invoiceId: `${this.workspace.name.toString()}`,
окей, занеси в список задач тогда

2021-02-02 11:46 UTC, neSpecc commented on src/i18n/messages/en.json
> +        "success": "Payment success",
Payment sent to processing

2021-02-02 11:46 UTC, neSpecc commented on src/components/modals/ProcessPaymentDialog.vue
> +        // @todo add i18n message
```suggestion
        /**
         * @todo add i18n message
         */
```

2021-02-02 11:46 UTC, neSpecc commented on src/components/modals/ProcessPaymentDialog.vue
> +      // @todo set lang from user's Hawk setting
```suggestion
      /**
       * @todo set lang from user's Hawk setting
       */
```

2021-02-02 11:46 UTC, neSpecc commented on src/i18n/messages/ru.json
> +        "success": "Платеж успешно выполнен",
```suggestion
        "success": "Платеж передан в обработку",
```

2021-02-02 14:41 UTC, neSpecc approved these changes

2021-02-02 14:45 UTC, nikmel2803 approved these changes

2021-02-02 14:47 UTC, merged