Billing: get payment data before charge
codex-team/hawk.garage pull request #362
Opened 2021-02-06 08:55 UTC by khaydarov

2021-02-07 18:58 UTC, neSpecc requested changes

2021-02-07 18:58 UTC, neSpecc commented on src/components/modals/ProcessPaymentDialog.vue
> +  async charge(response) {
showPaymentWidget

2021-02-07 18:58 UTC, neSpecc commented on src/components/modals/ProcessPaymentDialog.vue
> +const METHOD_CHARGE = 'charge';
убрать неиспользуемое

2021-02-09 13:42 UTC, neSpecc commented on src/components/modals/ProcessPaymentDialog.vue
>          } as PlanProlongationPayload,
вот этот тип еще надо изменить. Почему он не ругается?

2021-02-09 13:43 UTC, nikmel2803 commented on src/components/modals/ProcessPaymentDialog.vue
> +const METHOD_BEFOREPAY = 'beforePay';
может лучше сделаем `before-pay`

2021-02-09 13:43 UTC, nikmel2803 commented on src/types/before-payment-payload.ts
> +  tariff: string;
```suggestion
  tariffPlanId: string;
```

2021-02-09 13:43 UTC, nikmel2803 commented on src/components/modals/ProcessPaymentDialog.vue
> +  async charge(response) {
может передавать сразу `data: BeforePaymentPayload`?

2021-02-09 15:14 UTC, khaydarov commented on src/types/before-payment-payload.ts
> +  tariff: string;
description: `Payment for tariff "${data.tariff}" for ${this.workspace.name.toString()} workspace for a month`

tariff вроде используется в description как текст или нормально что отправится id?

2021-02-09 15:24 UTC, nikmel2803 commented on src/components/modals/ProcessPaymentDialog.vue
> +  }
```suggestion
  async processPayment() {
    const response = await axios.get(`${API_SERVER}/compose-payment?workspaceId=${this.workspace.id}`);
    this.showPaymentWidget(response.data as BeforePaymentPayload)
  }
```

2021-02-11 20:42 UTC, neSpecc approved these changes

2021-02-12 09:13 UTC, nikmel2803 requested changes

2021-02-12 09:13 UTC, nikmel2803 commented on src/components/modals/ProcessPaymentDialog.vue
> +    const response = await axios.get(`${API_SERVER}/compose-payment?workspaceId=${this.workspace.id}`);
может лучше `API_REST_ENDPOINT`?
а ещё тут не отправляется `tariffId`

2021-02-12 09:13 UTC, nikmel2803 commented on .env.sample
> +VUE_APP_REST_SERVER=http://localhost:4000
Может не будет делать ещё одну переменную? Чтобы не усложнять конфигурацию. Да и смысла особого нет. Лучше сделать один `VUE_APP_API_ENDPOINT=http://localhost:4000`, а `/graphql` добавить в строчку 110 файла `src/api/index.ts`:

```ts
    promise = axios.post(API_ENDPOINT + '/graphql', formData);

```

2021-02-12 09:13 UTC, nikmel2803 commented on src/components/modals/ProcessPaymentDialog.vue
> +        description: `Payment for tariff "${data.tariffId}" for ${this.workspace.name.toString()} workspace for a month`,
пользователь не должен видеть id

2021-02-13 21:14 UTC, khaydarov commented on .env.sample
> +VUE_APP_REST_SERVER=http://localhost:4000
согласен, не стал так делать изначально чтобы сильно не менять ничего

2021-02-15 08:07 UTC, nikmel2803 commented on src/components/modals/ProcessPaymentDialog.vue
> +        description: `Payment for tariff "${data.plan.name}" for ${this.workspace.name.toString()} workspace for a month`,
выглядит вроде норм
только в реквесте в апи я не вижу, что возвращается поле plan
![image](https://user-images.githubusercontent.com/32655339/107920110-72a5dd80-6f7d-11eb-94e7-821ec7e5d115.png)

2021-02-17 08:14 UTC, talyguryn approved these changes

2021-02-17 18:32 UTC, nikmel2803 approved these changes

2021-02-17 18:33 UTC, merged