Feature/new billing
codex-team/hawk.garage pull request #366
Opened 2021-02-16 13:14 UTC by kebyo

New Billing

2021-02-16 16:10 UTC, neSpecc requested changes

2021-02-16 16:10 UTC, neSpecc commented on src/components/workspace/settings/BillingOverview.vue
> +        class="billing-card__workspace-blocked"
У нас уже есть элемент с таким дизайном (Настройки проекта / Уведомления / Excluding word) —  надо вынести его в универсальный компонент 

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/3684889/108088202-3f507500-7089-11eb-9828-39400c2b4fc0.png">

2021-02-16 16:10 UTC, neSpecc commented on src/components/workspace/settings/BillingOverview.vue
> +     * Return a valid buttons
```suggestion
     * Return buttons list depended on workspace state.
```

2021-02-16 16:10 UTC, neSpecc commented on src/components/workspace/settings/BillingOverview.vue
> +      if (!this.workspace.autoPay) {
тут надо бы добавить комментов для всех кейсов

2021-02-16 16:10 UTC, neSpecc commented on src/components/workspace/settings/BillingOverview.vue
> +    isVolumeSpent(): boolean {
```suggestion
    isEventsLimitExceeded(): boolean {
```

2021-02-16 16:10 UTC, neSpecc commented on src/components/workspace/settings/BillingOverview.vue
> +      return this.workspace.plan.eventsLimit === this.workspace.billingPeriodEventsCount;
```suggestion
      return this.workspace.plan.eventsLimit <= this.workspace.billingPeriodEventsCount;
```

2021-02-16 16:10 UTC, neSpecc commented on src/types/workspaces.ts
> +  subValidTill?: string;
у нас есть поле lastChargeDate (как-то так), к нему надо прибавить 30

2021-02-16 16:10 UTC, neSpecc commented on src/types/workspaces.ts
> +  autoPay: boolean;
по-моему, поле называется subscriptionId, уточни у @nikmel2803

2021-02-23 17:47 UTC, neSpecc approved these changes

2021-02-23 17:47 UTC, neSpecc commented on src/components/workspace/settings/BillingOverview.vue
> +      {{ 'Autopay is on.The next payment date:' }} {{ subExpiredDate | prettyDateFromDateTimeString }}
```suggestion
      {{ 'Autopay is on. The next payment date:' }} {{ subExpiredDate | prettyDateFromDateTimeString }}
```
тут не пропущено `$t`?

2021-02-23 17:47 UTC, neSpecc commented on src/components/workspace/settings/BillingOverview.vue
> +      incrementEventsLimit: {
надо добавить описания

2021-02-23 17:47 UTC, neSpecc commented on src/i18n/messages/ru.json
> +      "ownedWorkspaces": "Собственные воркспейсы"
а где используется owned? Я вроде менял это на managed

2021-02-23 17:47 UTC, neSpecc requested changes
Не туда нажал

2021-02-23 18:01 UTC, kebyo commented on src/i18n/messages/ru.json
> +      "ownedWorkspaces": "Собственные воркспейсы"
Личный кабинет - биллинг
![image](https://user-images.githubusercontent.com/64841603/108886649-442d9f80-761a-11eb-8e1a-3e763c471b34.png)

2021-02-23 18:02 UTC, neSpecc commented on src/i18n/messages/ru.json
> +      "ownedWorkspaces": "Собственные воркспейсы"
там тоже надо поменять на managedWorkspaces

2021-02-23 18:12 UTC, ilyamore88 commented on src/components/workspace/settings/AttentionSign.vue
> +<style lang="postcss">
Не обязательно указывать lang
```suggestion
<style>
```

2021-02-23 19:00 UTC, ilyamore88 approved these changes

2021-02-25 15:27 UTC, neSpecc commented on src/components/account/settings/Billing.vue
> +    const updatedWorkspaces: Workspace[] = [];
не понимаю, что здесь происходит. Где используется эта переменная?

2021-02-25 15:27 UTC, neSpecc commented on src/components/utils/billing/History.vue
> +      font-size: 12px;
это точно необходимо? в макетах, по-моему, 14

2021-02-25 15:27 UTC, neSpecc commented on src/components/workspace/settings/AttentionSign.vue
> +<template>
я думаю это лучше через svg сделать

2021-02-25 15:27 UTC, neSpecc commented on src/components/workspace/settings/BillingOverview.vue
> +      v-if="plan.name !== 'Startup' && isAutoPayOn"
откуда слово Startup? давай вынесем в метод или computed `isFreePlan`

2021-02-25 15:27 UTC, neSpecc commented on src/components/workspace/settings/BillingOverview.vue
> +    buttons(): Button[] {
можешь создать в сторибуки стори для всех кейсов? чтобы протестить эти проверки

2021-02-25 15:27 UTC, neSpecc commented on src/components/workspace/settings/Layout.vue
> +    try {
почему тут изменилось?

2021-02-25 15:58 UTC, kebyo commented on src/components/utils/billing/History.vue
> +      font-size: 12px;
![image](https://user-images.githubusercontent.com/64841603/109179930-731f4f00-779b-11eb-97df-2131eb935669.png)

2021-02-25 16:22 UTC, kebyo commented on src/components/workspace/settings/Layout.vue
> +    try {
Потому что, если сначала зайти в настройки воркспейся, данные не грузятся и поэтому я отправляю запрос

2021-02-26 12:44 UTC, neSpecc requested changes

2021-02-26 12:44 UTC, neSpecc commented on src/components/account/settings/Billing.vue
> +    const updatedWorkspaces: Workspace[] = [];
опиши в комментарии, зачем дом запросы в базу. Чем это отличается от `managedWorkspaces`, которые уже загружены?

2021-02-26 12:44 UTC, neSpecc commented on src/components/utils/billing/History.vue
> +      font-size: 12px;
тут написано `__tab`, а ты показываешь макет заголовка, стили которого кстати подключаются так `@apply --ui-label;`

2021-02-26 12:44 UTC, neSpecc commented on src/components/workspace/settings/Layout.vue
> +    try {
какие данные не грузятся? как воспроизвести?

2021-02-27 16:21 UTC, nikmel2803 approved these changes

2021-03-02 12:58 UTC, neSpecc approved these changes

2021-03-02 13:10 UTC, merged