Fix/change to free plan
codex-team/hawk.garage pull request #373
Opened 2021-03-06 16:31 UTC by kebyo

Closes #369

2021-03-06 17:42 UTC, ilyamore88 requested changes

2021-03-06 17:42 UTC, ilyamore88 commented on src/components/modals/ChooseTariffPlanPopup.vue
> +      if (this.plans.find(plan => plan.id === this.selectedPlan)?.monthlyCharge === 0) {
Выглядит жутко и нечитаемо. Лучше вынести `find` до `if`. А ещё лучше хранить в `selectedPlan` объект целиком, а не только его ID (я за второй вариант)

2021-03-06 17:42 UTC, ilyamore88 commented on src/components/modals/ChooseTariffPlanPopup.vue
> +        this.currentPlan = this.selectedPlan;
И в `currentPlan` тоже хранить объект целиком

2021-03-07 08:07 UTC, ilyamore88 requested changes

2021-03-07 08:07 UTC, ilyamore88 commented on src/components/modals/ChooseTariffPlanPopup.vue
>         * Id of selected plan
```suggestion
       * Selected plan object
```

2021-03-07 08:07 UTC, ilyamore88 commented on src/components/modals/ChooseTariffPlanPopup.vue
>         * Current plan id
```suggestion
       * Current plan object
```

2021-03-07 11:23 UTC, ilyamore88 approved these changes

2021-03-08 11:41 UTC, ilyamore88 requested changes
После переключения на бесплатный тарифный план popup зависает в таком состоянии
![image](https://user-images.githubusercontent.com/37909603/110316761-374a7c00-801c-11eb-8677-0bcc69c068a7.png)

Мне кажется, что надо закрывать это окно после смены тарифа.

2021-03-08 16:41 UTC, neSpecc requested changes

2021-03-08 16:41 UTC, neSpecc commented on src/api/workspaces/queries.ts
> +          name
а зачем тут столько полей? это будет сложно поддерживать. Надо вынести во фрагмент

2021-03-10 12:02 UTC, ilyamore88 approved these changes

2021-03-11 04:34 UTC, nikmel2803 requested changes

2021-03-11 04:34 UTC, nikmel2803 commented on src/api/workspaces/queries.ts
> +          ...WorkspacePlan
судя по коду экшена, который отвечает за смену тарифного плана, ты не используешь никакие данные из этой мутации. может тогда и оставить только recordId, а record убрать отсюда?

2021-03-11 04:34 UTC, nikmel2803 commented on src/api/fragments.ts
> +export const WORKSPACE_PROJECTS = `
Это где-то ещё используется в реквесте?
если нет, стоит убрать

2021-03-12 12:53 UTC, nikmel2803 approved these changes

2021-03-12 13:09 UTC, neSpecc requested changes

2021-03-12 13:09 UTC, neSpecc commented on src/api/workspaces/index.ts
> +  return api.call(MUTATION_CHANGE_WORKSPACE_PLAN_FOR_FREE_PLAN, {
название функции тоже надо поменять тогда

2021-03-14 10:47 UTC, neSpecc commented on src/components/modals/ChooseTariffPlanPopup.vue
> +      if (this.selectedPlan.monthlyCharge === 0) {
тут не хватает какого-то шага с подтверждением, "Сменить план на бесплатный? Да/Нет". Можно сделать отдельной задачей, только занеси это куда-то (issue+в roadmap)

2021-03-14 10:47 UTC, neSpecc commented on src/store/modules/workspaces/index.js
> +      plan: getters.getPlanById(result.record.plan.id),
тут нельзя просто `plan: result.record.plan`?

2021-03-14 10:49 UTC, GeekaN2 approved these changes

2021-03-16 13:53 UTC, merged