Feature/payment details modal
codex-team/hawk.garage pull request #383
Opened 2021-03-16 14:37 UTC by kebyo

Add payment details modal

2021-03-16 15:15 UTC, nikmel2803 requested changes
- кажется, что снизу паддинг сильно больше, чем в макете
- поля ввода в макете не на всю ширину диалога
- можешь, пожалуйста, перенести код для открытия виджета оплаты из старого диалога, чтобы не ломать уже существующую функциональность. Вроде там реально только скопировать и навесить обработчик на кнопку.

2021-03-16 20:54 UTC, nikmel2803 commented on src/components/modals/PaymentDetailsDialog.vue
> +  }
у нас где-то задаются глобальные стили, надо перенести это туда
где-то там уже модифицируются стили уведомлений

2021-03-16 20:54 UTC, nikmel2803 commented on src/components/modals/PaymentDetailsDialog.vue
> +      console.log('Res', response);
надо убрать

2021-03-16 20:54 UTC, nikmel2803 commented on src/components/modals/PaymentDetailsDialog.vue
> +        {
подумал, что может стоит и сюда тоже передать email?
https://developers.cloudpayments.ru/#parametry
1) cloudpayments скорее всего отправит пользователю уведомление
2) и может нам самим пригодится

2021-03-18 10:13 UTC, ilyamore88 reviewed
Я бы добавил логотипу ссылку на сайт CP
![image](https://user-images.githubusercontent.com/37909603/111609554-7c746800-87eb-11eb-8a94-5101b1c2552f.png)

Выравнивание по левому краю не ровное
![image](https://user-images.githubusercontent.com/37909603/111609712-9f9f1780-87eb-11eb-83f4-d0bf5d96da23.png)

У воркспейса разные цвета иконки
![image](https://user-images.githubusercontent.com/37909603/111609762-aded3380-87eb-11eb-9ae7-91a30ab25a2f.png)
![image](https://user-images.githubusercontent.com/37909603/111609791-b3e31480-87eb-11eb-9e63-8a1bcf358dab.png)

2021-03-18 17:24 UTC, neSpecc commented on src/assets/sprite-icons/cloud-payments-logo.svg
> +            <g>
лишние группы можно поудалять

2021-03-18 17:24 UTC, neSpecc commented on src/i18n/messages/ru.json
> +      "description": "Вы собираетесь приобрести месячный план для вашего воркспейса. Ваш платеж будет защищен. Мы не будем получать доступ и хранить данные о ваших банковских переводах. Вы получите ч
```suggestion
      "description": "Вы собираетесь оплатить тарифный план воркспейса. Ваш платеж будет защищен. Мы не не храним данные вашей банковской карты и не имеем к ним доступа. Вы получите чек на электронную почту. Больше информации об оплате — в документе.",
```

2021-03-18 17:24 UTC, neSpecc commented on src/i18n/messages/en.json
> +      "didNotAccept": "To pay you need to accept the payment agreement"
```suggestion
      "didNotAccept": "You need to accept the payment agreement to proceed with payment"
```

2021-03-18 17:24 UTC, neSpecc commented on src/i18n/messages/ru.json
> +      "description": "Вы собираетесь подписаться на автоматическое продление текущего плана воркспейса. Это означает, что при наступлении следующей даты платежа плановая цена будет автоматически снят
```suggestion
      "description": "Вы собираетесь подписаться на автоматическое продление текущего плана воркспейса. Это означает, что при наступлении следующей даты платежа стоимость плана будет автоматически списана с вашей карты. Подробнее читайте в документации.",
```

2021-03-18 17:24 UTC, neSpecc commented on src/i18n/messages/ru.json
> +      "acceptRecurrentPaymentAgreement": "Я понимаю и принимаю соглашение о автоматических платежах",
```suggestion
      "acceptRecurrentPaymentAgreement": "Я понимаю и принимаю соглашение об автоматических платежах",
```

2021-03-18 17:24 UTC, neSpecc commented on src/i18n/messages/ru.json
> +      "allowingChargesEveryMonth": "Я разрешаю списания с моей банковской карты каждый месяц"
```suggestion
      "allowingChargesEveryMonth": "Я разрешаю ежемесячные списания с моей банковской карты"
```

2021-03-21 12:46 UTC, nikmel2803 requested changes
- при нажатии на переключатель Auto-pay ничего не происходит

2021-03-22 08:32 UTC, nikmel2803 requested changes

2021-03-22 08:32 UTC, nikmel2803 commented on src/components/modals/PaymentDetailsDialog.vue
> +    nextPaymentDateString(): string {
доки

2021-03-22 08:32 UTC, nikmel2803 commented on src/components/modals/PaymentDetailsDialog.vue
> +      isAcceptedChargingEveryMonth: false,
доков нет

2021-03-22 08:32 UTC, nikmel2803 commented on src/components/modals/PaymentDetailsDialog.vue
> +    isAcceptedAllAgreements(): boolean {
доков нет

2021-03-22 08:32 UTC, nikmel2803 commented on src/components/modals/PaymentDetailsDialog.vue
> +        />
может вместо вызова метода, обернуть иконку в ссылку? так нативнее

2021-03-25 07:09 UTC, nikmel2803 commented on src/components/workspace/settings/BillingOverview.vue
> +      &-secondary {
это же модификаторы. должно быть __buttons--default и __buttons--primary

2021-03-25 07:09 UTC, nikmel2803 commented on src/components/modals/PaymentDetailsDialog.vue
> +        &__disabled {
и это тоже модификатор, поэтому --disabled

2021-03-26 06:22 UTC, nikmel2803 approved these changes

2021-03-26 07:29 UTC, ilyamore88 approved these changes
👍

2021-03-29 13:31 UTC, neSpecc approved these changes

2021-03-29 13:34 UTC, merged