Feature/route for workspace
codex-team/hawk.garage pull request #396
Opened 2021-04-17 07:02 UTC by kebyo

Close #253

2021-04-17 08:52 UTC, nikmel2803 requested changes

2021-04-17 08:52 UTC, nikmel2803 commented on src/components/AppShell.vue
> +
мне кажется, правильнее перенести это в какой-нибудь watch, например

2021-04-17 08:52 UTC, nikmel2803 commented on src/components/AppShell.vue
> +          :workspace-id="currentWorkspace.id"
я не очень понял зачем нужно это изменение

2021-04-17 08:52 UTC, nikmel2803 commented on src/components/aside/WorkspaceInfo.vue
> +    workspaceId: {
а зачем вообще менять этот файл?

2021-04-17 08:52 UTC, nikmel2803 commented on src/components/sidebar/Sidebar.vue
> +      });
есть мысль
что если не делать router.push после каждого dispatch, а поставить глобально watch на currentWorkspace (в appshell например) и при изменениях этого currentWorkspace пушить нужный роут

2021-04-18 18:10 UTC, nikmel2803 approved these changes

2021-04-18 19:24 UTC, ilyamore88 approved these changes

2021-04-19 09:36 UTC, nikmel2803 requested changes
— зайди в какой-нибудь проект
— переключи воркспейс
— проект закрылся, а он не должен

По идее, роут должен меняться на /workspace/id, если
1) пользователь был на /
2) пользователь был на /workspace/other-id
@neSpecc поправь, если ошибаюсь

2021-04-20 03:47 UTC, kebyo commented
> — зайди в какой-нибудь проект
> — переключи воркспейс
> — проект закрылся, а он не должен
> 
> По идее, роут должен меняться на /workspace/id, если
> 
> 1. пользователь был на /
> 2. пользователь был на /workspace/other-id
>    @neSpecc поправь, если ошибаюсь

@nikmel2803, а если я выбрал проект, а потом хочу кинуть ссылку на воркспейс, то мне придется открывать настройки и потом копировать url c id воркспейса, потому что после выбора проекта я не попаду на страницу с воркспейсом.

https://user-images.githubusercontent.com/64841603/115334435-10976d80-a1a4-11eb-95f5-458392d34aac.mov

2021-04-21 05:03 UTC, neSpecc commented on src/components/AppShell.vue
> +      if (this.$route.path === '/' || this.$route.path.includes('workspace')) {
опиши текстом, для чего эти проверки

2021-04-21 05:03 UTC, neSpecc commented on src/components/AppShell.vue
> +    currentWorkspace(workspace) {
опиши в доках плз, для чего добавлен этот метод (что он делает)

2021-04-21 09:59 UTC, neSpecc approved these changes

2021-04-21 10:08 UTC, nikmel2803 approved these changes

2021-04-21 13:50 UTC, merged