Cards saving and fetching
codex-team/hawk.garage pull request #407
Opened 2021-04-21 13:12 UTC by nikmel2803

now user can save cards during payment
saved cards are displayed in cards select and billing settings

closes #291 
closes #288

2021-04-21 16:02 UTC, ilyamore88 approved these changes

2021-04-21 16:02 UTC, ilyamore88 requested changes
Пофикси CI 🤢

2021-04-22 07:16 UTC, ilyamore88 approved these changes

2021-04-22 07:24 UTC, neSpecc approved these changes

2021-04-22 07:31 UTC, merged