[Feature] Confirmation window
codex-team/hawk.garage pull request #437
Opened 2021-05-27 04:35 UTC by ilyamore88

Implements confirmation window component.
Closes #259

2021-05-27 13:54 UTC, nikmel2803 approved these changes

2021-06-01 07:49 UTC, nikmel2803 commented on src/components/utils/ConfirmationWindow/ConfirmationWindowsOptions.ts
> +  deletion?: boolean;
мне кажется, стоит добавить is перед этими пропами
и я так понимаю, окно не может быть одновременно двух типов, поэтому я бы предложил сделать поле actionType: 'delete' | 'submit'

2021-06-01 08:53 UTC, neSpecc requested changes

2021-06-01 08:53 UTC, neSpecc commented on src/components/utils/ConfirmationWindow/ConfirmationWindow.vue
> +export default Vue.extend({
Please add an example of usage. Maybe README with docs in the folder of this component

2021-06-01 15:47 UTC, nikmel2803 approved these changes

2021-06-01 15:48 UTC, neSpecc commented on src/components/utils/ConfirmationWindow/ConfirmationWindow.vue
> +      actionType: 'submit',
why not using `enum` ?

2021-06-02 11:22 UTC, neSpecc approved these changes

2021-06-02 11:25 UTC, merged