Bump webpack and catcher versions
codex-team/hawk.garage pull request #484
Opened 2021-08-23 19:44 UTC by GeekaN2

2021-08-24 08:57 UTC, ilyamore88 approved these changes

2021-08-24 15:21 UTC, neSpecc requested changes

2021-08-24 15:21 UTC, neSpecc commented on vue.config.js
> +      repo: './',
is it necessary?

2021-08-25 13:35 UTC, neSpecc approved these changes

2021-08-25 13:35 UTC, merged