Feature/event notification
codex-team/hawk.garage pull request #518
Opened 2021-08-27 16:59 UTC by robonetphy

resolves #400 
includes #411

2021-08-28 09:49 UTC, neSpecc commented
<img width="432" alt="image" src="https://user-images.githubusercontent.com/3684889/131214000-7d4cbcdf-0390-456a-b75c-d7cb0cf8a75d.png">

2021-08-28 09:51 UTC, neSpecc commented
Let's open workspace billing page by clicking on this element 
<img width="73" alt="image" src="https://user-images.githubusercontent.com/3684889/131214042-cc24a20b-417a-4b2a-860f-d3eeb8d665df.png">

2021-08-28 10:00 UTC, neSpecc requested changes

2021-08-28 10:00 UTC, neSpecc commented on src/components/aside/WorkspaceInfo.vue
> +  }
lets add small animation here

2021-09-03 07:25 UTC, talyguryn approved these changes

2021-09-07 13:03 UTC, neSpecc commented
<img width="311" alt="image" src="https://user-images.githubusercontent.com/3684889/132349316-c7aef988-5f0e-46e3-aca0-c5310dc8ec2c.png">

2021-09-21 18:16 UTC, GeekaN2 commented
Try to somehow bind the position of the arrow to the circle
![image](https://user-images.githubusercontent.com/40016207/134225369-6099e14c-626d-45c1-b595-05afb2b62bdc.png)

2021-09-23 19:32 UTC, GeekaN2 commented on src/components/aside/WorkspaceInfo.vue
>        </router-link>
Also add `v-if= "isAdmin"`. Because you can't go to the billing page without admin rights

2021-09-23 19:44 UTC, GeekaN2 commented
I can't click on `boost!`, because the tooltip immediately disappears as soon as I take the mouse away from the circle. 
You need to create a small area on top of the tooltip and a little around the circle so that you can safely drive the mouse in them. 
<img width="370" alt="изображение" src="https://user-images.githubusercontent.com/40016207/134573262-02e22eab-481d-4904-be3e-04b1edda1bcb.png">

2021-09-23 19:48 UTC, GeekaN2 commented
Design is a bit different :
Now: 
<img width="438" alt="изображение" src="https://user-images.githubusercontent.com/40016207/134573932-2e2d4afc-dc0b-4e55-975d-5a95c470f2b2.png">
Want:
<img width="466" alt="изображение" src="https://user-images.githubusercontent.com/40016207/134573869-4274cd75-645d-403d-8a79-61432fac8334.png">

2021-09-23 19:49 UTC, GeekaN2 commented on src/components/aside/EventsLimitIndicator.vue
> +        <div class="events-limi__events">
```suggestion
        <div class="events-limit__events">
```

2021-09-23 19:54 UTC, GeekaN2 commented on src/components/aside/EventsLimitIndicator.vue
> +      const PERCENT = this.eventsCount / this.plan.eventsLimit;
There is no percentage stored here. It is better to rename

2021-09-23 19:54 UTC, GeekaN2 commented on src/components/aside/EventsLimitIndicator.vue
> +      return PERCENT >= 0.9;
Need to put `0.9` in a constant and call it something.

2021-10-01 10:01 UTC, neSpecc approved these changes

2021-10-01 10:25 UTC, talyguryn approved these changes
no questions, nice

2021-10-01 16:07 UTC, GeekaN2 reviewed
Everything is fine, but improve the boost button a little please

2021-10-01 16:07 UTC, GeekaN2 commented on src/components/aside/EventsLimitIndicator.vue
> +  }
And add `cursor: pointer` (If necessary) because it's supposed to be a button.

2021-10-01 16:07 UTC, GeekaN2 commented on src/components/aside/EventsLimitIndicator.vue
> +        />
Wrap to 
```
<router-link
  v-if="isAdmin"
  :to="{
    name: 'workspace-settings-billing',
    params: { workspaceId: workspace.id },
  }"
>
```
To go to the billing page by clicking

2021-10-01 17:00 UTC, GeekaN2 approved these changes

2021-10-01 17:30 UTC, merged