fix the troubles with plan while creating a new workspace
codex-team/hawk.garage pull request #565
Opened 2021-12-20 19:48 UTC by robonetphy

resolve #545

2022-01-12 10:30 UTC, neSpecc requested changes
You can just add the `plan` field in GraphQL `createWorkspace` mutation response. Use the `WORKSPACE_PLAN` for that.

Something like that:


```ts
export const MUTATION_CREATE_WORKSPACE = `
  mutation createWorkspace(
    $name: String!,
    $image: Upload
  ) {
    workspace: createWorkspace(name: $name, image: $image) {
      id
      name
      description
      image
      inviteHash
      ...WorkspaceWithTeam
      ...WorkspacePlan
    }
  }

  ${WORKSPACE_FRAGMENT_WITH_TEAM}
  ${WORKSPACE_PLAN}
`;
```

2022-01-12 15:05 UTC, robonetphy commented
> ```ts
> ...WorkspacePlan
> ```

Actually, I guess in our API backend we are not assigning these plans and we are directly changing in db as [here](https://github.com/codex-team/hawk.api.nodejs/blob/489d36d37428fa2a176a8f9a65b51e16d0ff3684/src/models/workspacesFactory.ts#L54-L73)
And I tried the same earlier getting error as below:
![image](https://user-images.githubusercontent.com/23169768/149165525-8ee4b0f5-ba25-4b61-be9c-0cb1f9b97b34.png)

2022-01-12 15:13 UTC, neSpecc commented
> ```ts
> ```ts
> ...WorkspacePlan
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> Actually, I guess in our API backend we are not assigning these plans and we are directly changing in db as here
> And I tried the same earlier getting error as below:
> ```

Looks like we need to update the Workspace model in `changePlan` method as well as the db update.

2022-01-24 19:34 UTC, ilyamore88 approved these changes

2022-01-26 18:10 UTC, neSpecc approved these changes

2022-01-27 17:26 UTC, merged