feat: replace BillingInformation with the UsedVolume
codex-team/hawk.garage pull request #607
Opened 2022-12-09 08:59 UTC by HyTekCoop

Resolves #605
Billing Information page is not up to date, it was decided to replace it with Used Volume page. Billing Information page has been disabled from Account/settings and Workspace/settings. Also Boost button has been disabled.
Used Volume page has been created to replace Billing Information page. And bug related to the CircleProgress has been fixed.

2022-12-09 13:06 UTC, neSpecc requested changes

2022-12-09 13:06 UTC, neSpecc commented on package.json
>    "dependencies": {
you've updated all the major versions of dependencies. It's not the safe change. I'd suggest to rollback.

2022-12-09 13:06 UTC, neSpecc commented on src/components/workspace/settings/BillingOverview.vue
> +<!--          />-->
I think this change is not related because you're disabling the BillingOverview page at all, isn't it?

2022-12-09 13:06 UTC, neSpecc commented on src/components/workspace/settings/UsedVolume.vue
> +    <div class="workspace-volume__text">We have no paid plans, so all features is available fo free.
Use the `i18n` wrapper for UI texts please

2022-12-09 13:06 UTC, neSpecc commented on src/components/workspace/settings/UsedVolume.vue
> +  margin-bottom: 30px;
wrong indentation

2022-12-09 13:06 UTC, neSpecc commented on src/router.ts
> +            // },
Let's leave this route, but add a redirect to the used-volume page.

2022-12-22 09:37 UTC, neSpecc commented on src/components/workspace/settings/UsedVolume.vue
> +      <div class="button workspace-volume__button">{{ $t('workspaces.settings.volume.emailButton') }}</div>
redundant `div`, you can add `button workspace-volume__button` classes to the `a` tag

2022-12-22 09:37 UTC, neSpecc commented on src/components/workspace/settings/UsedVolume.vue
> +  color: var(--color-text-second);
wrong identation

2022-12-22 09:37 UTC, neSpecc commented on src/i18n/messages/en.json
> +        "description_1": "We have no prepaid plans. All features are available for free. The limit of accepted events is 500 000 events per month.",
> 500 000

we need to check the exact limit we have. Is it really 500 000 or less?

2022-12-22 20:20 UTC, neSpecc approved these changes

2022-12-23 11:02 UTC, nikmel2803 approved these changes

2022-12-24 10:51 UTC, merged